import "./globals.css";
import { jakarta_bold, jakarta_regular, jakarta_semibold, jakarta_medium } from "@/fonts";


export const metadata = {
    title: "Hayase",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={jakarta_regular.className}>{children}</body>
        </html>
    );
}
